DROP TABLE IF EXISTS artists;

CREATE TABLE artists(
  id SERIAL PRIMARY KEY NOT NULL,
  artist VARCHAR(255) NOT NULL,
  rate DECIMAL NOT NULL,
  streams INTEGER NOT NULL,
  payout VARCHAR(50) NOT NULL
);